//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalisisAcademico.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class catCarreraAsignaturasCursadas
    {
        public int id { get; set; }
        public string AsignaturasTotales { get; set; }
        public string AsignaturasAprobadas { get; set; }
        public string AsignaturasReprobadas { get; set; }
        public string AsignaturasPorCursar { get; set; }
        public string AsignaturasRepeticion { get; set; }
        public string PorcentajeAvance { get; set; }
    }
}
