//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalisisAcademico.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento_Solicitud
    {
        public int idSolicitud { get; set; }
        public int idDocumento { get; set; }
        public Nullable<System.DateTime> fechaAsignacion { get; set; }
    
        public virtual Documento Documento { get; set; }
        public virtual Solicitud Solicitud { get; set; }
    }
}
