//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalisisAcademico.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngresoInstitucional
    {
        public int id { get; set; }
        public string periodoIngreso { get; set; }
        public string modoIngreso { get; set; }
        public string periodoReinscripcion { get; set; }
        public string semestre { get; set; }
        public int idAlumno { get; set; }
    
        public virtual SegUsuarios SegUsuarios { get; set; }
    }
}
