//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalisisAcademico.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensajes
    {
        public int idMensaje { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idNotificacion { get; set; }
        public Nullable<int> idPersonalAdministrativo { get; set; }
        public string strMensaje { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual Notificaciones Notificaciones { get; set; }
        public virtual SegPersonalAdministrativo SegPersonalAdministrativo { get; set; }
        public virtual SegUsuarios SegUsuarios { get; set; }
    }
}
