//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalisisAcademico.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SegUsuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SegUsuarios()
        {
            this.AlumnoEstatusAcademico = new HashSet<AlumnoEstatusAcademico>();
            this.Asignaturas = new HashSet<Asignaturas>();
            this.Creditos = new HashSet<Creditos>();
            this.EspecialAsignaturas = new HashSet<EspecialAsignaturas>();
            this.EspecialAsignaturasAcreditadas = new HashSet<EspecialAsignaturasAcreditadas>();
            this.IngresoInstitucional = new HashSet<IngresoInstitucional>();
            this.Mensajes = new HashSet<Mensajes>();
            this.Seguimiento = new HashSet<Seguimiento>();
            this.Solicitud = new HashSet<Solicitud>();
            this.SolicitudDeAlumno = new HashSet<SolicitudDeAlumno>();
        }
    
        public int id { get; set; }
        public string strNombre { get; set; }
        public string strAPaterno { get; set; }
        public string strAMaterno { get; set; }
        public string strPlanEstudios { get; set; }
        public string email { get; set; }
        public string strUsuario { get; set; }
        public string strPassword { get; set; }
        public string strMatricula { get; set; }
        public string strSemestreActual { get; set; }
        public string strTelefono { get; set; }
        public Nullable<int> idSegPerfil { get; set; }
        public byte[] foto { get; set; }
        public Nullable<int> idCarrera { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlumnoEstatusAcademico> AlumnoEstatusAcademico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asignaturas> Asignaturas { get; set; }
        public virtual CatCarrera CatCarrera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Creditos> Creditos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EspecialAsignaturas> EspecialAsignaturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EspecialAsignaturasAcreditadas> EspecialAsignaturasAcreditadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngresoInstitucional> IngresoInstitucional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mensajes> Mensajes { get; set; }
        public virtual SegPerfil SegPerfil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguimiento> Seguimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud> Solicitud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudDeAlumno> SolicitudDeAlumno { get; set; }
    }
}
