//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalisisAcademico.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudDeAlumno
    {
        public int id { get; set; }
        public Nullable<int> idSolicitud { get; set; }
        public Nullable<int> idAlumno { get; set; }
        public Nullable<System.DateTime> fechaAprovacion { get; set; }
        public string comentarios { get; set; }
    
        public virtual SegUsuarios SegUsuarios { get; set; }
        public virtual Solicitud Solicitud { get; set; }
    }
}
