//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalisisAcademico.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Solicitud()
        {
            this.Documento_Solicitud = new HashSet<Documento_Solicitud>();
            this.Notificaciones = new HashSet<Notificaciones>();
            this.SolicitudDeAlumno = new HashSet<SolicitudDeAlumno>();
        }
    
        public int idSolicitud { get; set; }
        public Nullable<int> idCatAsuntoSolicitud { get; set; }
        public string motivos { get; set; }
        public Nullable<System.DateTime> fechaSolicitud { get; set; }
        public Nullable<int> idStatus { get; set; }
        public string folioSolicitud { get; set; }
        public int idAlumno { get; set; }
    
        public virtual CatAsuntoSolicitud CatAsuntoSolicitud { get; set; }
        public virtual CatStatus CatStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documento_Solicitud> Documento_Solicitud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notificaciones> Notificaciones { get; set; }
        public virtual SegUsuarios SegUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudDeAlumno> SolicitudDeAlumno { get; set; }
    }
}
