//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalisisAcademico.Web {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Recursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recursos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnalisisAcademico.Web.Recursos", typeof(Recursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Admisión.
        /// </summary>
        public static string Admision {
            get {
                return ResourceManager.GetString("Admision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo crear el archivo de forma adecuada.
        /// </summary>
        public static string MES_ERROR_CREAR_ARCHIVO {
            get {
                return ResourceManager.GetString("MES_ERROR_CREAR_ARCHIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de Inicio de Sesion..
        /// </summary>
        public static string MES_ERROR_LOGIN {
            get {
                return ResourceManager.GetString("MES_ERROR_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe ningun archivo cargado.
        /// </summary>
        public static string MES_NINGUN_ARCHIVO_SELECCIONADO {
            get {
                return ResourceManager.GetString("MES_NINGUN_ARCHIVO_SELECCIONADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo fue  modificado exitosamente.
        /// </summary>
        public static string MOODIFICACION_EXITOSA {
            get {
                return ResourceManager.GetString("MOODIFICACION_EXITOSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /Documentos.
        /// </summary>
        public static string RUTA_DIRECTORIO {
            get {
                return ResourceManager.GetString("RUTA_DIRECTORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptada.
        /// </summary>
        public static string STATUS_ACEPTADA {
            get {
                return ResourceManager.GetString("STATUS_ACEPTADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelada.
        /// </summary>
        public static string STATUS_CANCELADA {
            get {
                return ResourceManager.GetString("STATUS_CANCELADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Denegada.
        /// </summary>
        public static string STATUS_DENEGADA {
            get {
                return ResourceManager.GetString("STATUS_DENEGADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activa.
        /// </summary>
        public static string STATUS_INICIAL_ACTIVA {
            get {
                return ResourceManager.GetString("STATUS_INICIAL_ACTIVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En Proceso.
        /// </summary>
        public static string STATUS_PROCESO {
            get {
                return ResourceManager.GetString("STATUS_PROCESO", resourceCulture);
            }
        }
    }
}
