//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Academico.Common {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Recursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recursos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Academico.Common.Recursos", typeof(Recursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        internal static string ACCIONAGREGAR {
            get {
                return ResourceManager.GetString("ACCIONAGREGAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.
        /// </summary>
        internal static string DIRECTOR_CARRERA {
            get {
                return ResourceManager.GetString("DIRECTOR_CARRERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los Datos Se Guardaron Correctamente.
        /// </summary>
        internal static string EDICION_EXITOSA {
            get {
                return ResourceManager.GetString("EDICION_EXITOSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.
        /// </summary>
        internal static string EN_PROCESO {
            get {
                return ResourceManager.GetString("EN_PROCESO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se Pudieron Editar  tus Datos, Intenta nuevamente..
        /// </summary>
        internal static string FALLO_EDICION {
            get {
                return ResourceManager.GetString("FALLO_EDICION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se Pudieron Guardar tus Datos, Intenta nuevamente..
        /// </summary>
        internal static string FALLO_GUARDADO {
            get {
                return ResourceManager.GetString("FALLO_GUARDADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ctl00$ContentPlaceHolder1$.
        /// </summary>
        internal static string ID_CLIENTE_UNIQUE_CONTROL {
            get {
                return ResourceManager.GetString("ID_CLIENTE_UNIQUE_CONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3.
        /// </summary>
        internal static string ID_PERFIL_ALUMNO {
            get {
                return ResourceManager.GetString("ID_PERFIL_ALUMNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deberás llenar todos  los campos del formulario.
        /// </summary>
        internal static string LLENAR_FORMULARIO_COMPLETO {
            get {
                return ResourceManager.GetString("LLENAR_FORMULARIO_COMPLETO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a manager.
        /// </summary>
        internal static string MANAGER {
            get {
                return ResourceManager.GetString("MANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Modo Edición].
        /// </summary>
        internal static string MODO_EDICION {
            get {
                return ResourceManager.GetString("MODO_EDICION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Modo Guardar].
        /// </summary>
        internal static string MODO_GUARDADO {
            get {
                return ResourceManager.GetString("MODO_GUARDADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Documentos/.
        /// </summary>
        internal static string PATH_DOCUMENTOS {
            get {
                return ResourceManager.GetString("PATH_DOCUMENTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/imagenes/Usuarios/.
        /// </summary>
        internal static string PATH_IMAGENES {
            get {
                return ResourceManager.GetString("PATH_IMAGENES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alumno.
        /// </summary>
        internal static string PERFIL_ALUMNO {
            get {
                return ResourceManager.GetString("PERFIL_ALUMNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Browser.
        /// </summary>
        internal static string RUTAAPP {
            get {
                return ResourceManager.GetString("RUTAAPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a seguimiento.
        /// </summary>
        internal static string SEGUIMIENTO {
            get {
                return ResourceManager.GetString("SEGUIMIENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro esta incompleto: 0%, es obligatorio llenar el formulario..
        /// </summary>
        internal static string SEGUIMIENTO_REGISTRO_INCOMPLETO {
            get {
                return ResourceManager.GetString("SEGUIMIENTO_REGISTRO_INCOMPLETO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debés Seleccionar una Opción Valida..
        /// </summary>
        internal static string SELECCIONAR_OPCION {
            get {
                return ResourceManager.GetString("SELECCIONAR_OPCION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a usuario.
        /// </summary>
        internal static string USER {
            get {
                return ResourceManager.GetString("USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a directivo.
        /// </summary>
        internal static string USER_DIR_CARRERA {
            get {
                return ResourceManager.GetString("USER_DIR_CARRERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El  Nombre de  Usuario ya Existe, Prueba con Otro Nombre..
        /// </summary>
        internal static string USUARIO_DUPLICADO {
            get {
                return ResourceManager.GetString("USUARIO_DUPLICADO", resourceCulture);
            }
        }
    }
}
